workspace:
  base: /go
  path: src/github.com/justinbarrick/flux-operator

pipeline:
  build:
    image: golang:1.10-alpine
    commands:
      - apk update && apk add make git
      - make generate-crds
      - echo "Checking if generated files are different than commited, will fail if changes are detected."
      - git diff --exit-code
      - make test
      - make build
    when:
      event: push

  test:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ SSH_KEY ]
    environment:
      - KUBECONFIG=/go/.kube/config
      - DOCKER_HOST=tcp://minikube:2375
    commands:
      - ./integration-test.sh
    when:
      event: push

  publish:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ DOCKER_USER, DOCKER_PASSWORD ]
    environment:
      - DOCKER_HOST=tcp://minikube:2375
      - TAG=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    commands:
      - ./push.sh
    when:
      branch: master
      event: push

services:
  minikube:
    image: justinbarrick/drone-minikube:localkube
    privileged: true
    commands:
    - echo nameserver 8.8.8.8 > /etc/resolv.conf
    - /usr/local/bin/docker-entrypoint.sh start
    when:
      event: push
