workspace:
  base: /go
  path: flux-operator


pipeline:
  build-cache-dl:
    image: justinbarrick/drone-rclone:latest
    pull: true
    privileged: true
    secrets: [AWS_ACCESS_KEY, AWS_SECRET_KEY]
    mount: .go
    endpoint: https://codesink-cache.nyc3.digitaloceanspaces.com
    provider: DigitalOcean

  build:
    image: golang:1.11-stretch
    commands:
      - make generate-openapi
      - echo "Checking if generated files are different than commited, will fail if changes are detected."
      - git diff --exit-code
      - make test
      - make build
      - make fluxopctl
    environment:
      - GOPATH=/go/flux-operator/.go
      - CGO_ENABLED=0
      - GO111MODULE=on
    when:
      event: [push, tag]
      ref:
        exclude: [refs/tags/flux-sync-*]

  build-cache-up:
    image: justinbarrick/drone-rclone:latest
    pull: true
    privileged: true
    secrets: [AWS_ACCESS_KEY, AWS_SECRET_KEY]
    mount: .go
    endpoint: https://codesink-cache.nyc3.digitaloceanspaces.com
    provider: DigitalOcean
    upload: true

  test:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ SSH_KEY ]
    environment:
      - KUBECONFIG=/go/.kube/config
      - DOCKER_HOST=tcp://minikube:2375
    commands:
      - ./integration-test.sh
    when:
      event: [push, tag]
      ref:
        exclude: [refs/tags/flux-sync-*]

  publish-dev:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ DOCKER_USER, DOCKER_PASSWORD ]
    environment:
      - DOCKER_HOST=tcp://minikube:2375
      - TAG=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    commands:
      - ./push.sh
    when:
      event: push

  publish:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ DOCKER_USER, DOCKER_PASSWORD ]
    environment:
      - DOCKER_HOST=tcp://minikube:2375
      - TAG=${DRONE_TAG}
    commands:
      - ./push.sh
    when:
      branch: master
      event: tag

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - flux-operator
      - fluxopctl
    checksum:
      - sha256
    when:
      branch: master
      event: tag

  lint-crds:
    image: golang:1.11-stretch
    commands:
      - make generate-crds
      - echo "Checking if generated files are different than commited, will fail if changes are detected."
      - git diff --exit-code
    when:
      event: [push, tag]
      ref:
        exclude: [refs/tags/flux-sync-*]

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: '#kubernetes'
    username: Drone CI
    icon_url: https://i.imgur.com/B7Tk2Xf.png
    when:
      status: [success, failure]
      event: [push, tag]
      ref:
        exclude: [refs/tags/flux-sync-*]

    template: >
      {{#success build.status}}
        Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} succeeded!
      {{else}}
        Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} failed.
      {{/success}}

  slack-push:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: '#kubernetes'
    username: Drone CI Docker Push
    icon_url: https://i.imgur.com/B7Tk2Xf.png
    when:
      event: push
    template: >
      Pushed <https://hub.docker.com/r/{{repo.owner}}/{{repo.name}}|{{repo.owner}}/{{repo.name}}:${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}> to Dockerhub.

  slack-tag:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: '#kubernetes'
    username: Flux-operator Release Bot
    icon_url: https://i.imgur.com/B7Tk2Xf.png
    when:
      branch: master
      event: tag
    template: >
      Released ${DRONE_TAG} to <https://github.com/{{repo.owner}}/{{repo.name}}/releases/tag/${DRONE_TAG}|Github>.

      Pushed <https://hub.docker.com/r/{{repo.owner}}/{{repo.name}}|{{repo.owner}}/{{repo.name}}:${DRONE_TAG}> to Dockerhub.

services:
  minikube:
    image: justinbarrick/drone-minikube:localkube
    privileged: true
    commands:
    - echo nameserver 8.8.8.8 > /etc/resolv.conf
    - /usr/local/bin/docker-entrypoint.sh start
    when:
      event: [push, tag]
      ref:
        exclude: [refs/tags/flux-sync-*]
