workspace:
  base: /go
  path: src/github.com/justinbarrick/flux-operator

pipeline:
  build:
    image: golang:1.10-alpine
    commands:
      - apk update && apk add make git
      - make generate-crds
      - echo "Checking if generated files are different than commited, will fail if changes are detected."
      - git diff --exit-code
      - make test
      - make build
    when:
      event: push

  test:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ SSH_KEY ]
    environment:
      - KUBECONFIG=/go/.kube/config
      - DOCKER_HOST=tcp://minikube:2375
    commands:
      - ./integration-test.sh
    when:
      event: push

  publish:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ DOCKER_USER, DOCKER_PASSWORD ]
    environment:
      - DOCKER_HOST=tcp://minikube:2375
      - TAG=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    commands:
      - ./push.sh
    when:
      branch: master
      event: push

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: '#kubernetes'
    username: Drone CI
    icon_url: https://i.imgur.com/B7Tk2Xf.png
    when:
      status: [success, failure]
      event: push
    template: >
      {{#success build.status}}
        Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} succeeded!
        {{#master build.branch}}
        Pushed <https://hub.docker.com/r/{{repo.owner}}/{{repo.name}}|{{repo.owner}}/{{repo.name}}:${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}> to Dockerhub.
        {{/master}}
      {{else}}
        Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} failed.
      {{/success}}

services:
  minikube:
    image: justinbarrick/drone-minikube:localkube
    privileged: true
    commands:
    - echo nameserver 8.8.8.8 > /etc/resolv.conf
    - /usr/local/bin/docker-entrypoint.sh start
    when:
      event: push
