apiVersion: "flux.codesink.net/v1alpha1"
kind: "Flux"
metadata:
  name: "example"
  namespace: default
spec:
  gitUrl: ssh://git@github.com/justinbarrick/flux-operator
  gitBranch: minikube
  gitPath: deploy/flux-example/
  gitPollInterval: 0m30s
  helmOperator:
    enabled: false
    chartPath: deploy/chart-example/
  tiller:
    enabled: false
  clusterRole:
    enabled: true
  role:
    enabled: true
