kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-operator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flux-operator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
- nonResourceURLs: ['*']
  verbs: ['*']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-flux-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: flux-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-flux-operator
subjects:
- kind: ServiceAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux-operator
  template:
    metadata:
      labels:
        name: flux-operator
    spec:
      containers:
        - name: flux-operator
          image: justinbarrick/flux-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
