apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux-operator
  template:
    metadata:
      labels:
        name: flux-operator
    spec:
      containers:
        - name: flux-operator
          image: justinbarrick/flux-operator
          command:
          - flux-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
